import type { CheckCategory, CheckConfigType, CheckLifecycle, VerificationType } from "@/lib/types";

export interface AvailableCheck {
  name: string;
  categories: CheckCategory[];
  defaultRequired: boolean;
  defaultEnabled: boolean;
  lifecycle?: CheckLifecycle;
  configurable?: boolean;
  requiresBiometric?: boolean;
  configType?: CheckConfigType;
}

export const AVAILABLE_CHECKS: Record<VerificationType, AvailableCheck[]> = {
  government_id: [
    { name: "Account comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Age comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "age_range" },
    { name: "Allowed country", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "country" },
    { name: "Allowed ID type", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "id_type" },
    { name: "Attribute comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Barcode", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "barcode" },
    { name: "Barcode inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Blur", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Color", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Compromised submission", categories: ["fraud"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Damaged detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Double side", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Electronic replica", categories: ["fraud"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Expiration", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "expiration" },
    { name: "Extracted properties", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "extracted_properties" },
    { name: "Extraction inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Fabrication", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Glare", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Government ID", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Handwriting", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "ID image tampering", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "ID number format inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "ID physical tampering", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "ID-to-Selfie comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Inconsistent repeat", categories: ["fraud"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "repeat" },
    { name: "Inquiry comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "MRZ detected", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "MRZ inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Paper detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "PO box", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Portrait", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Portrait age", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Portrait clarity", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Processable submission", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Public figure", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "REAL ID", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Repeat", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "repeat" },
    { name: "Valid dates", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
  ],
  selfie: [
    { name: "Center present", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Face comparison", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Liveness", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Pose repeat", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Selfie account comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Selfie attribute comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Selfie duplicate", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Selfie glasses", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Selfie ID comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Selfie pose", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Selfie suspicious", categories: ["fraud"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
  ],
  database: [
    { name: "Database inquiry comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "Database address match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Database date of birth match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Database name match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Database phone match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Database SSN match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  document: [
    { name: "Document attribute comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "Document date of birth comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "Document disallowed country", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "country" },
    { name: "Document duplicate detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Document extraction", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Document inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Document name comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "Document tampering", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Document type detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "id_type" },
    { name: "Document valid", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
  ],
  aamva: [
    { name: "AAMVA address match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "AAMVA date of birth match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA expiration check", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA issuing authority match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA license number match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA name match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
  ],
  database_phone_carrier: [
    { name: "Phone number active", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Carrier match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Carrier risk score", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Name match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Address match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  database_ssn: [
    { name: "SSN match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "SSN issuance check", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Name match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Date of birth match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Address match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
  ],
  email_address: [
    { name: "Email deliverable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Email domain valid", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Email not disposable", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Email age check", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Email breach database", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
  ],
  phone_number: [
    { name: "Phone number valid", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "OTP verified", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Phone not VoIP", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Carrier lookup", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Phone country match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  health_insurance_card: [
    { name: "Card readable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card not expired", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Issuer recognized", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Member ID extraction", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
  ],
  vehicle_insurance: [
    { name: "Card readable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Policy not expired", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Insurer recognized", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "VIN extraction", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Policy number extraction", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
  ],
};
