import type { CheckCategory, CheckLifecycle, VerificationType } from "@/lib/types";

export interface AvailableCheck {
  name: string;
  category: CheckCategory;
  defaultRequired: boolean;
  defaultEnabled: boolean;
  lifecycle?: CheckLifecycle;
  configurable?: boolean;
}

export const AVAILABLE_CHECKS: Record<VerificationType, AvailableCheck[]> = {
  government_id: [
    { name: "Account comparison", category: "validity", defaultRequired: false, defaultEnabled: true, configurable: true },
    { name: "Age comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Allowed country", category: "validity", defaultRequired: true, defaultEnabled: true, configurable: true },
    { name: "Allowed ID type", category: "validity", defaultRequired: true, defaultEnabled: true, configurable: true },
    { name: "Attribute comparison", category: "validity", defaultRequired: false, defaultEnabled: true, configurable: true },
    { name: "Barcode", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Barcode inconsistency", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Blur", category: "validity", defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Color", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Compromised submission", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "Damaged detection", category: "validity", defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Double side", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Electronic replica", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "Expiration", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Extracted properties", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Extraction inconsistency", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Fabrication", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "Glare", category: "validity", defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Government ID", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Handwriting", category: "validity", defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "ID image tampering", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "ID number format inconsistency", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "ID physical tampering", category: "fraud", defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "ID-to-Selfie comparison", category: "biometrics", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Inconsistent repeat", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Inquiry comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "MRZ detected", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "MRZ inconsistency", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Paper detection", category: "fraud", defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "PO box", category: "validity", defaultRequired: false, defaultEnabled: false },
    { name: "Portrait", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Portrait age", category: "biometrics", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Portrait clarity", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Processable submission", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Public figure", category: "fraud", defaultRequired: false, defaultEnabled: false },
    { name: "REAL ID", category: "validity", defaultRequired: false, defaultEnabled: false },
    { name: "Repeat", category: "fraud", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Valid dates", category: "validity", defaultRequired: false, defaultEnabled: true },
  ],
  selfie: [
    { name: "Center present", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Face comparison", category: "biometrics", defaultRequired: true, defaultEnabled: true },
    { name: "Liveness", category: "biometrics", defaultRequired: true, defaultEnabled: true },
    { name: "Pose repeat", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Selfie account comparison", category: "biometrics", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Selfie attribute comparison", category: "biometrics", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Selfie duplicate", category: "fraud", defaultRequired: false, defaultEnabled: false },
    { name: "Selfie glasses", category: "biometrics", defaultRequired: false, defaultEnabled: false },
    { name: "Selfie ID comparison", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Selfie pose", category: "biometrics", defaultRequired: false, defaultEnabled: true },
    { name: "Selfie suspicious", category: "fraud", defaultRequired: false, defaultEnabled: true },
  ],
  database: [
    { name: "Database inquiry comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Database address match", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Database date of birth match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Database name match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Database phone match", category: "validity", defaultRequired: false, defaultEnabled: false },
    { name: "Database SSN match", category: "validity", defaultRequired: false, defaultEnabled: false },
  ],
  document: [
    { name: "Document attribute comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Document date of birth comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Document disallowed country", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Document duplicate detection", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Document extraction", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Document inconsistency", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Document name comparison", category: "validity", defaultRequired: false, defaultEnabled: false, configurable: true },
    { name: "Document tampering", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "Document type detection", category: "validity", defaultRequired: false, defaultEnabled: true, configurable: true },
    { name: "Document valid", category: "validity", defaultRequired: true, defaultEnabled: true },
  ],
  aamva: [
    { name: "AAMVA address match", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "AAMVA date of birth match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA expiration check", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA issuing authority match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA license number match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA name match", category: "validity", defaultRequired: true, defaultEnabled: true },
  ],
  database_phone_carrier: [
    { name: "Phone number active", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Carrier match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Carrier risk score", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Name match", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Address match", category: "validity", defaultRequired: false, defaultEnabled: false },
  ],
  database_ssn: [
    { name: "SSN match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "SSN issuance check", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Name match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Date of birth match", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Address match", category: "validity", defaultRequired: true, defaultEnabled: true },
  ],
  email_address: [
    { name: "Email deliverable", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Email domain valid", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Email not disposable", category: "fraud", defaultRequired: true, defaultEnabled: true },
    { name: "Email age check", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Email breach database", category: "fraud", defaultRequired: false, defaultEnabled: false },
  ],
  phone_number: [
    { name: "Phone number valid", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "OTP verified", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Phone not VoIP", category: "fraud", defaultRequired: false, defaultEnabled: true },
    { name: "Carrier lookup", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Phone country match", category: "validity", defaultRequired: false, defaultEnabled: false },
  ],
  health_insurance_card: [
    { name: "Card readable", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Card not expired", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Issuer recognized", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Member ID extraction", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", category: "fraud", defaultRequired: false, defaultEnabled: true },
  ],
  vehicle_insurance: [
    { name: "Card readable", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Policy not expired", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Insurer recognized", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "VIN extraction", category: "validity", defaultRequired: false, defaultEnabled: true },
    { name: "Policy number extraction", category: "validity", defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", category: "fraud", defaultRequired: false, defaultEnabled: true },
  ],
};
