import type { CheckCategory, CheckConfigType, CheckLifecycle, VerificationType } from "@/lib/types";

export interface AvailableCheck {
  name: string;
  categories: CheckCategory[];
  defaultRequired: boolean;
  defaultEnabled: boolean;
  lifecycle?: CheckLifecycle;
  configurable?: boolean;
  requiresBiometric?: boolean;
  configType?: CheckConfigType;
}

export const AVAILABLE_CHECKS: Record<VerificationType, AvailableCheck[]> = {
  government_id: [
    { name: "Account comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Age comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "age_range" },
    { name: "Allowed country", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "country" },
    { name: "Allowed ID type", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "id_type" },
    { name: "Attribute comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Barcode", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "barcode" },
    { name: "Barcode inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Blur", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Color", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Compromised submission", categories: ["fraud"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Damaged detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Double side", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Electronic replica", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Expiration", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "expiration" },
    { name: "Extracted properties", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "extracted_properties" },
    { name: "Extraction inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Fabrication", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Glare", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Government ID", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Handwriting", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "ID image tampering", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "ID number format inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "ID physical tampering", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "ID-to-Selfie comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Inconsistent repeat", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Inquiry comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "MRZ detected", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, configurable: true, configType: "mrz" },
    { name: "MRZ inconsistency", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Paper detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "PO box", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Portrait", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Portrait age", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Portrait clarity", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true, requiresBiometric: true },
    { name: "Processable submission", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Public figure", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "REAL ID", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Repeat", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Valid dates", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
  ],
  selfie: [
    { name: "Account comparison", categories: ["user_action_required", "fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Age comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true, configurable: true, configType: "age_range" },
    { name: "Attribute comparison", categories: ["user_action_required", "fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Face covering", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Glare", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "Glasses", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Image quality", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, lifecycle: "beta" },
    { name: "Multiple faces", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Portrait quality", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Pose position", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Pose repeat", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Public figure", categories: ["user_action_required", "fraud"], defaultRequired: false, defaultEnabled: false, requiresBiometric: true },
    { name: "Selfie liveness", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
    { name: "Selfie-to-ID comparison", categories: ["user_action_required", "fraud"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true, configurable: true, configType: "comparison" },
    { name: "Suspicious entity", categories: ["fraud"], defaultRequired: true, defaultEnabled: true, requiresBiometric: true },
  ],
  database: [
    { name: "Alive Detection", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Attribute comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Deliverable address", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "Identity Comparison", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true, configurable: true, configType: "comparison" },
    { name: "Inquiry comparison", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "comparison" },
    { name: "P.O. Box Detection", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Residential address", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "2+2 Detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  document: [
    { name: "Expired detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
    { name: "JPEG original image detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "Recency / Effective detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "expiration" },
    { name: "Extracted properties detection", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false, configurable: true, configType: "extracted_properties" },
    { name: "Compromised submission", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "Copy move detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "Document image tampering", categories: ["fraud"], defaultRequired: false, defaultEnabled: false, lifecycle: "sunset" },
    { name: "Image inconsistent timestamp detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "Image suspicious metadata detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "PDF abnormal font detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "PDF annotation detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "PDF content type detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "PDF editor detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
    { name: "PDF inconsistent timestamp detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
  ],
  aamva: [
    { name: "AAMVA address match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "AAMVA date of birth match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA expiration check", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA issuing authority match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA license number match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "AAMVA name match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
  ],
  database_phone_carrier: [
    { name: "Phone number active", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Carrier match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Carrier risk score", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Name match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Address match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  database_ssn: [
    { name: "SSN match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "SSN issuance check", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Name match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Date of birth match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Address match", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
  ],
  email_address: [
    { name: "Email deliverable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Email domain valid", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Email not disposable", categories: ["fraud"], defaultRequired: true, defaultEnabled: true },
    { name: "Email age check", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Email breach database", categories: ["fraud"], defaultRequired: false, defaultEnabled: false },
  ],
  phone_number: [
    { name: "Phone number valid", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "OTP verified", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Phone not VoIP", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
    { name: "Carrier lookup", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Phone country match", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: false },
  ],
  health_insurance_card: [
    { name: "Card readable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card not expired", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Issuer recognized", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Member ID extraction", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
  ],
  vehicle_insurance: [
    { name: "Card readable", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Policy not expired", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Insurer recognized", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "VIN extraction", categories: ["user_action_required"], defaultRequired: false, defaultEnabled: true },
    { name: "Policy number extraction", categories: ["user_action_required"], defaultRequired: true, defaultEnabled: true },
    { name: "Card tampering detection", categories: ["fraud"], defaultRequired: false, defaultEnabled: true },
  ],
};
